<a href="https://colab.research.google.com/github/Aneekcodes/Python/blob/main/Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Matrix Addition

Two Matrices can be added only if they have the same shape

In [2]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding two Matrices

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


In [9]:

# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [10]:

print(matrix_1)

print(matrix_2)

[[5 6 5]
 [6 9 4]
 [9 0 1]]
[[ 5 11 10]
 [11 13  7]
 [19  1  9]]


In [11]:
sum = np.add(matrix_1, matrix_2)


print(sum)

[[10 17 15]
 [17 22 11]
 [28  1 10]]


Matrix Subtraction

In [12]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [13]:
print(A)

[[2 3]
 [4 5]]


In [14]:
print(B)

[[6 7]
 [8 9]]


In [15]:
difference = A - B


print(difference)

[[-4 -4]
 [-4 -4]]


In [16]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [17]:
print(matrix_1)

print(matrix_2)

[[6 7 2]
 [0 6 3]
 [2 8 1]]
[[ 3  2 13]
 [ 1  2  6]
 [10 10  8]]


In [18]:
diff = np.subtract(matrix_1, matrix_2)


print(diff)

[[  3   5 -11]
 [ -1   4  -3]
 [ -8  -2  -7]]


Multiplying a matrix by a scalar

In [19]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[3 1 8 0]
 [5 1 7 8]
 [3 7 4 4]
 [6 2 1 6]]


In [20]:
product = np.multiply(x,y)

print(product)

[[15  5 40  0]
 [25  5 35 40]
 [15 35 20 20]
 [30 10  5 30]]


Multiplying 2 Matrices

In [21]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))


In [22]:
print(matrix_3)
print(matrix_4)

[[3 3 0]
 [2 1 2]
 [3 2 1]]
[[4 4 2 0]
 [3 2 0 4]
 [2 1 3 3]]


In [23]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[21 18  6 12]
 [15 12 10 10]
 [20 17  9 11]]


Element wise Matrix Multiplication

In [24]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [25]:
print(matrix_3)

[[4 2 1]
 [2 0 0]
 [1 0 1]]


In [26]:
print(matrix_4)

[[0 2 1]
 [4 4 3]
 [3 4 4]]


In [27]:
product = np.multiply(matrix_3, matrix_4)
print(product)

[[0 4 1]
 [8 0 0]
 [3 0 4]]
