<a href="https://colab.research.google.com/github/Aneekcodes/Python/blob/main/Matrix_Working.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Creating a Matrix using numpy

In [5]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)


[[2 3]
 [6 7]]


In [6]:
matrix_1.shape

(2, 2)

In [7]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [8]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values


In [9]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.19920703 0.05841505 0.46209184]
 [0.75616496 0.26327899 0.90170086]
 [0.86220944 0.33009579 0.55474736]]


In [10]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[80 97 88 46 52]
 [80 96 37 65 19]
 [61 86 39 26 52]
 [46 57 84 32 42]]


Matrix with all the values as 1

In [11]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [13]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [14]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [16]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [18]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[20 80 20 77  0]
 [51 72 39  7  7]
 [65 47 39 25 11]
 [48 21 59 66 36]]


In [19]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[20 51 65 48]
 [80 72 47 21]
 [20 39 39 59]
 [77  7 25 66]
 [ 0  7 11 36]]
