<a href="https://colab.research.google.com/github/Aneekcodes/Python/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

List vs Numpy(Time Taken)

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0010751970000004718


In [4]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time -start_time)

0.0005932130000001479


Numpy Arrays

In [5]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)


[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [8]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
b.shape

(2, 4)

In [14]:
c= np.array([(1,2,3,4), (5,6,7,8)] , dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [16]:
#numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#array of particular value
z = np.full((4,4),7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [21]:
#IDENTITY MATRIX (eye)
a= np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
b= np.random.random((3,4))
print(b)

[[0.59681896 0.54502221 0.02405405 0.08853665]
 [0.77964681 0.62990921 0.01966939 0.22149767]
 [0.13537636 0.59711573 0.75694359 0.53850917]]


In [23]:
c= np.random.randint(10,100,(3,5))
print(c)

[[47 27 99 20 26]
 [17 62 12 42 24]
 [14 22 34 18 32]]


In [24]:
d= np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [25]:
e= np.arange(10,30,5)
print(e)

[10 15 20 25]


In [26]:

list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)


[10 20 20 20 50]


numpy.ndarray

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)
# array dimension
print(c.shape)
# number of dimensions
print(c.ndim)
# number of elements in an array
print(c.size)
# checking the data type of the values in the array
print(c.dtype)

In [27]:
#Array Manipulation
array =np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 5 5]
 [5 3 6]]
(2, 3)


In [29]:
#transpose
trans = np.transpose(array)
print(trans)
print(array.shape)

[[3 5]
 [5 3]
 [5 6]]
(2, 3)


In [30]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 8 3]
 [0 0 3]]
(2, 3)


In [32]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 0]
 [8 0]
 [3 3]]
(3, 2)


In [33]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 9 4]
 [5 2 0]]
(2, 3)


In [34]:
b= a.reshape(3,2)
print(b)
print(b.shape)

[[4 9]
 [4 5]
 [2 0]]
(3, 2)
