## Starting with NumPy


In [ ]:
import numpy as np

In [ ]:
arr_1d=np.array([1,2,3,4])
print("2D array",arr_1d)

[1 2 3 4]


In [ ]:
arr_2d = np.array([[1,2,3,4],[2,4,5,6]])
print("2D array",arr_2d)

[[1 2 3 4]
 [2 4 5 6]]


## NumPy vs List


In [9]:
py_list = [1,2,3]
print("List Multiplication with scalar value: ",py_list*2)

np_list = np.array([1,2,3])
print("Array Multiplication with scalar value: ",np_list*2)

List Multiplication with scalar value:  [1, 2, 3, 1, 2, 3]
Array Multiplication with scalar value:  [2 4 6]


In [16]:
import time
start =time.time()
py_list =[i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time: ", time.time() -start)




 List operation time:  0.12173700332641602

 Numpy operation time:  0.008674144744873047


## Creating array from scratch


In [22]:
zeros = np.zeros((3,4))
print("zeros arrays : \n", zeros)

ones = np.ones((2,3))
print("ones array : \n", ones)

full = np.full((2,2),7)
print("full array : \n", full)

random =np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 10 , 2)
print("Sequence array: \n" , sequence)

zeros arrays : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array : 
 [[7 7]
 [7 7]]
random array: 
 [[0.1189554  0.88416515 0.45557609]
 [0.14008293 0.96003981 0.80784678]]
Sequence array: 
 [0 2 4 6 8]


## Vector , Matrix and Tensor


In [23]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]], 
                   [[5,6], [7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##Array properties


In [25]:
arr= np.array([[1,2,3], 
               [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Datatype ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Datatype  int32


### Array Reshaping

In [32]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array \n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

raveled = reshaped.ravel()
print("\n Raveled array ", raveled)

transpose = reshaped.T
print("\n Transpose array \n", transpose)


Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
