## Numpy Array Operations


In [ ]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire Row: ", arr_2d[1])
print("Entire Column:" , arr_2d[:, 1])


Specific element 6
Entire Row:  [4 5 6]
Entire Column: [2 5 8]


## Sorting

In [10]:
unsorted = np.array([3,4,2,5,1,8,6,7])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], 
                            [1,2],
                            [2,3]])
print("Sorted 2d Array", np.sort(arr_2d_unsorted, axis =0))

Sorted Array [1 2 3 4 5 6 7 8]
Sorted 2d Array [[1 1]
 [2 2]
 [3 3]]


## Filter

In [11]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 ==0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [12]:
mask = numbers >5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [15]:
indices =[0,2,4]
print(numbers[indices])

where_result = np.where(numbers >5 )
print(where_result)
print("NP where ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9], dtype=int64),)
NP where  [ 6  7  8  9 10]


In [16]:
condition_array = np.where(numbers >5 , "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data


In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility

In [18]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c =np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True
